# Generated by Django 3.2.8 on 2021-12-04 10:41

from django.db import migrations, models
import django.db.models.deletion
import website.models
import website.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=24, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('continent', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=220)),
                ('accuracy', models.FloatField(blank=True, default=0.0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=website.models.user_directory_path, validators=[website.validators.validate_file_extension])),
                ('human_guess', models.IntegerField()),
                ('real_value', models.IntegerField(blank=True, null=True)),
                ('correct_guess', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.user')),
            ],
            options={
                'verbose_name': 'Participant Image',
                'verbose_name_plural': 'Participants Images',
            },
        ),
    ]
